services:
    blog.admin.post:
        class: BlogBundle\Admin\PostAdmin
        arguments: [~, BlogBundle\Entity\Post, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Post }

    blog.admin.tag:
        class: BlogBundle\Admin\TagAdmin
        arguments: [~, BlogBundle\Entity\Tag, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Tag }

    blog.admin.comment:
        class: BlogBundle\Admin\CommentAdmin
        arguments: [~, BlogBundle\Entity\Comment, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Comment }
