services:
    blog.admin.post:
        class: BlogBundle\Admin\PostAdmin
        arguments: [~, BlogBundle\Entity\Post, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Blog", label: Post }

    blog.admin.tag:
        class: BlogBundle\Admin\TagAdmin
        arguments: [~, BlogBundle\Entity\Tag, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Blog", label: Tag }

    blog.admin.comment:
        class: BlogBundle\Admin\CommentAdmin
        arguments: [~, BlogBundle\Entity\Comment, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Blog", label: Comment }
